# ==========================================
# SPRING BOOT APPLICATION
# ==========================================
spring.application.name=nomos-inventory-service

# Asegura que el servicio se ejecute en un puerto diferente al de Auth Service (8080)
server.port=8082
# ==========================================
# BASE DE DATOS POSTGRESQL
# ==========================================
# (Asegúrate de cambiar los datos si tu DB de inventario es diferente a la de Auth)
spring.datasource.url=jdbc:postgresql://localhost:5432/nomos_inventory_db
spring.datasource.username=gonzalo
spring.datasource.password=2577705
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para la gestión de la base de datos
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ==========================================
# SEGURIDAD (Resource Server - Auth0 JWT)
# ==========================================
# Configuración esencial para que Spring sepa dónde verificar el JWT.

# URL del emisor (Issuer URI). Copiada de tu servicio Auth.
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-663twfpev8syoqq5.us.auth0.com/

# La Audience (Audience, 'aud' claim). Copiada de tu servicio Auth.
spring.security.oauth2.resourceserver.jwt.audience=https://nomos.inventory.api

# Nivel de debug para ver el proceso de autenticación del JWT
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,file:uploads/images/
spring.web.resources.add-mappings=true
server.base-url=http://localhost:8082